routes/web.php
<?php

Route::group(['middleware' => ['role:admin,manager']], function () {
    Route::get('dashboard', 'DashboardController@index')->name('home');

    //CurrencyController
    Route::get('dashboard/currency', 'CurrencyController@get');
    Route::get('dashboard/currency/update', 'CurrencyController@update');
    Route::get('dashboard/corona', 'SettingController@get');
    Route::get('dashboard/corona/create', 'SettingController@create');
    Route::get('dashboard/corona/edit/{id}', 'SettingController@edit');

    // VendorController
    Route::get('dashboard/vendor', 'VendorController@index');
    Route::get('dashboard/vendor/show/{id}', 'VendorController@show');
    Route::get('dashboard/vendor/create', 'VendorController@create');
    Route::get('dashboard/vendor/edit/{id}', 'VendorController@edit');
    Route::post('dashboard/vendor/store', 'VendorController@store');
    Route::put('dashboard/vendor/update/{id}', 'VendorController@update');
//    Route::delete('dashboard/vendor/delete/{id}', 'VendorController@delete');
    Route::get('dashboard/vendor/removeImage/{id}', 'VendorController@removeImage');
    Route::get('dashboard/vendor/switch/{alias}', 'VendorController@switch');

    Route::get('dashboard/message/order/{id}', 'MessageController@show');

    Route::get('dashboard/orders', 'OrderController@index');
    Route::get('dashboard/orders/show/{id}', 'OrderController@show');
    Route::get('dashboard/order/{id}/change/price', 'OrderController@changePrice');
    Route::get('dashboard/orders/create', 'OrderController@create');
    Route::get('dashboard/orders/edit/{id}', 'OrderController@edit');
    Route::post('dashboard/orders/store', 'OrderController@store');
    Route::put('dashboard/orders/update/{id}', 'OrderController@update');
//    Route::delete('dashboard/orders/delete/{id}', 'OrderController@delete');
    Route::get('dashboard/orders/removeImage/{id}', 'OrderController@removeImage');
    Route::get('dashboard/orders/switch/{id}', 'OrderController@switch');

    Route::get('dashboard/delivery', 'CarrierController@index');
    Route::get('dashboard/delivery/show/{id}', 'CarrierController@show');
    Route::get('dashboard/delivery/create', 'CarrierController@create');
    Route::get('dashboard/delivery/edit/{id}', 'CarrierController@edit');
    Route::post('dashboard/delivery/store', 'CarrierController@store');
    Route::put('dashboard/delivery/update/{id}', 'CarrierController@update');
    Route::get('dashboard/delivery/switch/{id}', 'CarrierController@switch');
    Route::get('dashboard/delivery/removeImage/{id}', 'CarrierController@removeImage');

    Route::get('dashboard/shipping', 'ShippingController@index');
    Route::get('dashboard/shipping/show/{id}', 'ShippingController@show');
    Route::get('dashboard/shipping/create', 'ShippingController@create');
    Route::get('dashboard/shipping/edit/{id}', 'ShippingController@edit');
    Route::post('dashboard/shipping/store', 'ShippingController@store');
    Route::put('dashboard/shipping/update/{id}', 'ShippingController@update');
    Route::get('dashboard/shipping/switch/{id}', 'ShippingController@switch');
    Route::get('dashboard/shipping/removeImage/{id}', 'ShippingController@removeImage');

    Route::get('dashboard/offer/shipping/{id}', 'ShippingOfferController@index');
    Route::get('dashboard/offer/create/shipping', 'ShippingOfferController@create');
    Route::get('dashboard/offer/shipping/edit/{id}', 'ShippingOfferController@edit');
    Route::post('dashboard/offer/shipping/store', 'ShippingOfferController@store');
    Route::put('dashboard/offer/shipping/update/{id}', 'ShippingOfferController@update');

    Route::get('dashboard/vendor/{vendorAlias}/product', 'ProductController@index');
    Route::get('dashboard/vendor/{vendorAlias}/product/show/{productAlias}', 'ProductController@show');
    Route::get('dashboard/vendor/{vendorAlias}/product/switch/{productAlias}', 'ProductController@switch');
    Route::get('dashboard/vendor/{vendorAlias}/product/recommend/switch/{productAlias}', 'ProductController@switchRecommend');
    Route::get('dashboard/vendor/{vendorAlias}/product/create', 'ProductController@create');
    Route::get('dashboard/vendor/{vendorAlias}/product/edit/{productAlias}', 'ProductController@edit');
    Route::post('dashboard/vendor/{vendorAlias}/product/store', 'ProductController@store');
    Route::put('dashboard/vendor/{vendorAlias}/product/update/{productAlias}', 'ProductController@update');
    Route::get('dashboard/product/removeImage/{id}', 'ProductController@removeImage');
    Route::get('dashboard/remove/vendor/{vendorAlias}/product/{productAlias}', 'ProductController@removeProduct');

    Route::get('dashboard/vendor/{vendorAlias}/product/{productAlias}', 'ProductSizeController@index');
    Route::get('dashboard/vendor/{vendorAlias}/product/size/{productAlias}/show/{productSizeAlias}',
        'ProductSizeController@show');
    Route::get('dashboard/vendor/{vendorAlias}/product/size/{productAlias}/switch/{productSizeAlias}',
        'ProductSizeController@switch');
    Route::get('dashboard/vendor/{vendorAlias}/product/size/{productAlias}/create', 'ProductSizeController@create');
    Route::get('dashboard/vendor/{vendorAlias}/product/size/{productAlias}/edit/{productSizeAlias}',
        'ProductSizeController@edit');
    Route::post('dashboard/vendor/{vendorAlias}/product/{productAlias}/store', 'ProductSizeController@store');
    Route::put('dashboard/vendor/{vendorAlias}/product/{productAlias}/update/{productSizeAlias}',
        'ProductSizeController@update');
    Route::get('dashboard/vendor/{vendorAlias}/product/{productAlias}/delete/{productSizeAlias}',
        'ProductSizeController@delete');
    Route::get('dashboard/size/removeImage/{productSizeAlias}', 'ProductSizeController@removeImage');

    Route::get('dashboard/vendor/{vendorAlias}/product/{productAlias}/{productSizeAlias}',
        'ProductSizeTypeController@index');
    Route::get('dashboard/switch/{productSizeTypeId}', 'ProductSizeTypeController@switch');
    Route::get('dashboard/vendor/{vendorAlias}/product/size/{productAlias}/{productSizeAlias}/create',
        'ProductSizeTypeController@create');
    Route::get('dashboard/vendor/{vendorAlias}/product/size/{productAlias}/{productSizeAlias}/edit/{productSizeTypeId}',
        'ProductSizeTypeController@edit');
    Route::post('dashboard/vendor/{vendorAlias}/product/{productAlias}/{productSizeAlias}/store',
        'ProductSizeTypeController@store');
    Route::put('dashboard/vendor/{vendorAlias}/product/{productAlias}/update/{productSizeAlias}/{productSizeTypeId}',
        'ProductSizeTypeController@update');
    Route::get('dashboard/size/type/removeImage/{productSizeAlias}', 'ProductSizeTypeController@removeImage');
    Route::get('dashboard/vendor/{vendorAlias}/product/{productAlias}/delete/{productSizeAlias}/{productSizeTypeId}',
        'ProductSizeTypeController@delete');
});
Route::group(['middleware' => ['role:admin']], function () {
    Route::get('/dashboard/banner', 'BannerController@index');
    Route::get('/dashboard/banner/create', 'BannerController@create');
    Route::get('/dashboard/banner/edit/{id}', 'BannerController@edit');
    Route::post('/dashboard/banner/store', 'BannerController@store');
    Route::put('/dashboard/banner/update/{id}', 'BannerController@update');
    Route::delete('/dashboard/banner/delete/{id}', 'BannerController@delete');

//    Route::get('dashboard/corona/delete/{id}', 'SettingController@coronaDelete');
    Route::post('dashboard/corona/store', 'SettingController@store');
    Route::put('dashboard/corona/update/{id}', 'SettingController@update');
    Route::get('dashboard/corona/refresh', 'SettingController@refreshCorona');
    Route::get('dashboard/corona/optimize', 'SettingController@optimize');

    Route::get('/dashboard/country', 'CountryController@index');
    Route::get('/dashboard/country/create', 'CountryController@create');
    Route::get('/dashboard/country/{id}/edit', 'CountryController@edit');
    Route::post('/dashboard/country/store', 'CountryController@store');
    Route::put('/dashboard/country/update/{id}', 'CountryController@update');
    Route::delete('/dashboard/country/delete/{id}', 'CountryController@delete');

    Route::get('/dashboard/country/{id}/city', 'CityController@index');
    Route::get('/dashboard/country/{id}/city/create', 'CityController@create');
    Route::get('/dashboard/country/{id}/city/edit', 'CityController@edit');
    Route::post('/dashboard/country/{id}/city/store', 'CityController@store');
    Route::put('/dashboard/country/{id}/city/update', 'CityController@update');
    Route::delete('/dashboard/country/{id}/city/delete', 'CityController@delete');


    // CategoryController
    Route::get('dashboard/category', 'CategoryController@index');
    Route::get('dashboard/category/show/{id}', 'CategoryController@show');
    Route::get('dashboard/category/create', 'CategoryController@create');
    Route::get('dashboard/category/edit/{id}', 'CategoryController@edit');
    Route::post('dashboard/category/store', 'CategoryController@store');
    Route::get('dashboard/category/toggle/{id}', 'CategoryController@toggleMain');
    Route::put('dashboard/category/update/{id}', 'CategoryController@update');
    Route::get('dashboard/category/removeImage/{id}', 'CategoryController@removeImage');

    Route::get('dashboard/manager', 'ManagerController@index');
    Route::get('dashboard/users', 'ManagerController@users');
    Route::get('dashboard/carriers', 'ManagerController@carriers');
    Route::get('dashboard/manager/create', 'ManagerController@create');
    Route::get('dashboard/user/carrier/create', 'ManagerController@createCarrier');
    Route::get('dashboard/manager/edit/{id}', 'ManagerController@edit');
    Route::post('dashboard/manager/store', 'ManagerController@store');
    Route::put('dashboard/manager/update/{id}', 'ManagerController@update');

app/Vendor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;

class Vendor extends Model
{
    use HasSlug;

    /**
     * Get the options for generating the slug.
     */
    public function getSlugOptions(): SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('name')
            ->saveSlugsTo('alias');
    }

    /**
     * Get the route key for the model.
     *
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'alias';
    }

    protected $guarded = [];

    public function country()
    {
        return $this->belongsTo('App\Country');
    }
    public function city()
    {
        return $this->belongsTo('App\City');
    }

    public function banner()
    {
        return $this->hasMany('App\Banner');
    }

    public function order()
    {
        return $this->hasMany('App\Order');
    }

    public function product()
    {
        return $this->hasMany('App\Product');
    }

    public function categories()
    {
        return $this->belongsToMany('App\Category', 'categories_vendor')->withTimestamps();
    }

    public function managers()
    {
        return $this->hasMany('App\User','user_id');
    }

    public function getImageAttribute()
    {
        $directory = "uploads/vendor/".$this->id;
        $images = \File::glob($directory."/*.jpg");
        if (count($images) > 0) {
            return $images;
        }
        return [asset('img/logo.svg')];
    }
}

resources/views/frontend/auth.blade.php
@extends('layouts.frontend')

@section('content')
    <div class="container">
        <div class="section-register">
            <div class="section-register-wrapper">
                <form action="{{action('AuthController@register')}}" method="POST" class="section-register-form">
                    @csrf
                    <div class="section-register-form__field first-field">
                    <legend class="section-register-form__field--legend">@lang('main.auth.0')</legend>
                        <div class="section-register-form__field--input">
                            <div class="section-register-form__field--input_item">
                                <div class="section-register-form__field--input-wrapper wrapper-register">
                                    <label for="name">@lang('main.auth.1')</label>
                                    <input type="text" id="name" name="name" />
                                </div>
                            </div>
                            <div class="section-register-form__field--input_item">
                                <div class="section-register-form__field--input-wrapper wrapper-register">
                                    <label for="mail">@lang('main.auth.2')</label>
                                    <input type="email" id="mail" name="email" placeholder="" />
                                </div>
                            </div>
                            <div class="section-register-form__field--input_item">
                                <div class="section-register-form__field--input-wrapper wrapper-register">
                                    <label for="phone">@lang('main.auth.3')</label>
                                    <input type="tel" id="phone" name="phone" placeholder="" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="section-register-form__field first-field">
                        <div class="section-register-form__field--input">
                            <div class="section-register-form__field--input_item">
                                <div class="section-register-form__field--input-wrapper wrapper-register">
                                    <label for="city">@lang('main.auth.4')</label>
                                    <input type="text" id="city" name="city" />
                                </div>
                                <div class="section-register-form__field--input-wrapper wrapper-register">
                                    <label for="country">@lang('main.auth.5')</label>
                                    <input type="text" id="country" name="country" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="section-register-form__field first-field">
                    <legend class="section-register-form__field--legend">@lang('main.auth.6')</legend>
                        <div class="section-register-form__field--input">
                            <div class="section-register-form__field--input_item">
                                <div class="section-register-form__field--input-wrapper wrapper-register">
                                    <label for="password">@lang('main.auth.7')</label>
                                    <input type="password" id="password" name="password" />
                                </div>
                                <div class="section-register-form__field--input-wrapper wrapper-register">
                                    <label for="confirm_password">@lang('main.auth.8')</label>
                                    <input type="password" id="confirm_password" name="password_confirmation" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="section-register-form__submit">
                        <input type="submit" value="@lang('main.auth.9')">
                    </div>

                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/frontend/category.blade.php
@extends('layouts.frontend')

@section('content')
    <br>
    <div class="category">
        <div class="container">
            <div class="category__all">@lang('main.nav.7')</div>
            <div class="d-flex flex-wrap category__wrap justify-content-between">
                @foreach($categories as $category)
                    <a href="{{action('PageController@category',$category->alias)}}" class="category__block">
                        <img src="{{asset($category->image)}}" alt="image"/>
                        <span class="title">
                    <span class="inside"> {{$category->name}}</span>
                </span>
                    </a>
                @endforeach
            </div>
        </div>
    </div>
@endsection

resources/views/frontend/collection.blade.php
@extends('layouts.frontend')

@section('content')
    <br>
    <div class="section-product">
        <div class="container">
            <div class="category__all">Сборники</div>
            <div class="section-product-wrapper collections__all">
                @foreach($collections as $collection)
                    <div class="collections d-flex align-items-center justify-content-between">
                        <div class="collections-inner">
                            <div class="title">{{$collection->name}}</div>
                            <div class="description">{{$collection->description}}</div>
                            <a href="{{action('PageController@showCollection',$collection->id)}}" class="btn">Посмотреть
                                больше</a>
                        </div>
                        <div class="collections-right d-flex align-items-center justify-content-end">
                            @foreach($collection->products as $key => $product)
                                @if($key < 4)
                                    @include('partials.product')
                                @endif
                            @endforeach
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </div>
    <br>
@endsection

resources/views/frontend/company.blade.php
@extends('layouts.frontend')

@section('content')
    <div class="container">
        <div class="info-companies">
            <div class="info-companies__top company">
                <div class="company__left organization">
                    <div class="organization__logo">
                        <img src="{{asset('/img/logo-company.svg')}}" alt="company" class="organization__logo-img"/>
                    </div>
                    <div class="organization__info">
                        <div class="organization__name">OAO “Jasur Metalurg LTD”</div>
                        <div class="organization__info-item">
                            <div class="organization__info-left">Сферы работы</div>
                            <div class="organization__info-right">Ulugbek Alimov</div>
                        </div>
                        <div class="organization__info-item">
                            <div class="organization__info-left">Дата открытия</div>
                            <div class="organization__info-right">09.08.1990</div>
                        </div>
                        <div class="organization__info-item">
                            <div class="organization__info-left">Номер телефона</div>
                            <div class="organization__info-right">+99899 881 80 60</div>
                        </div>
                        <div class="organization__info-item">
                            <div class="organization__info-left">Банк</div>
                            <div class="organization__info-right">Ipateka Bank</div>
                        </div>
                    </div>
                </div>
                <div class="company__right">
                    <div class="company-info">
                        <div class="company-info__table">
                            <div>
                                <div class="company-info__table-top">Кол-во сотрудников</div>
                                <div>500 - 700</div>
                            </div>
                            <div>
                                <div class="company-info__table-top">Страна</div>
                                <div>50 - 70</div>
                            </div>
                            <div class="company-info__table-last">
                                <div class="company-info__table-top">Описание</div>
                                <div>Отсутствует</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="section-product">
                <div class="section-product-wrapper">
                    <div class="main-title">Ещё от производителя
                    </div>
                    <div class="container">
                        <div class="row d-flex flex-grow">
{{--                            @foreach($product->vendor->product as $product_like)--}}
{{--                                @if($product_like->id != $product->id)--}}
{{--                                    <a class="product"--}}
{{--                                       href="{{action('PageController@showProduct',[$product_like->vendor->alias,$product_like->alias])}}">--}}
{{--                                        <div class="product__top">--}}
{{--                                            <img src="{{ asset($product_like->image[0]) }}" alt="product">--}}
{{--                                        </div>--}}
{{--                                        <div class="product__bottom">--}}
{{--                                            <div class="title">{{$product_like->name}}</div>--}}
{{--                                            <div--}}
{{--                                                class="price">{{ count($product_like->range) > 1 ? number_format($product_like->range[0]).' - '.number_format($product_like->range[1]) : number_format($product_like->range[0])  }}--}}
{{--                                                UZS--}}
{{--                                            </div>--}}
{{--                                            <div class="count">--}}
{{--                                                <span class="gray">Мин. заказ:</span>--}}
{{--                                                <b class="bold">{{$product_like->min_count}}</b>--}}
{{--                                                <span class="gray">{{$product_like->count_type ?? 'шт'}}</span>--}}
{{--                                            </div>--}}
{{--                                        </div>--}}
{{--                                    </a>--}}
{{--                                @endif--}}
{{--                            @endforeach--}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>

@endsection

resources/views/frontend/message.blade.php
@extends('layouts.frontend')

@section('content')
    <div class="container">
        <br>
        <a href="{{action('PageController@messages')}}">
            <div class="category__all">@lang('main.messages.1')</div>
        </a>
        <br>
        <div class="messages no-scroll" style="overflow: auto;">
            <div class="block">
                <div class="image"></div>
                <div class="info">
                    <div class="flex-1">
                        <div class="bold">№ {{$order->id}}</div>
                        <div class="bold m-10">{{$order->order_item[0]->name}}</div>
                    </div>
                    <div class="date">
                        <div class="bold">@lang('main.messages.2'): {{$order->price}} UZS</div>
                        {{--                        <div class="bold m-10">{{\Carbon\Carbon::parse($order->created_at)->format('d-m-yy')}}</div>--}}
                    </div>
                </div>
            </div>
        </div>
        <div class="order-items__wrap">
            @foreach($order->order_item as $item)
                <a href="{{action('PageController@showProduct',[$item->product->vendor->alias ,$item->product->alias] )}}" class="order-items d-flex align-items-center justify-content-between flex-wrap">
                    <div class="left">
                        <img src="{{$item->product->image[0]}}" width="100" alt="">
                    </div>
                    <div class="right d-flex align-items-center justify-content-between">
                        <div class="name">{{$item->product->name}}</div>
                        <div class="count">{{$item->amount}} {{ $item->product->count_type }}</div>
                        <div class="price">{{$item->price}} UZS</div>
                    </div>
                </a>
            @endforeach
        </div>
        <div class="messages-list">
            @foreach($messages as $message)
                @if($message->user_id != Auth::user()->id)
                    <div class="message-item another">
                        @if(count($message->image))
                            <a href="{{asset($message->image[0])}}" target="_blank">
                                <img src="{{asset($message->image[0])}}" alt="image">
                            </a>
                        @endif
                        <p>{{$message->body}} </p>
                    </div>
                @else
                    <div class="message-item own">
                        @if(count($message->image))
                            <a href="{{asset($message->image[0])}}" target="_blank">
                                <img src="{{asset($message->image[0])}}" alt="image">
                            </a>
                        @endif
                        <p>{{$message->body}}</p>
                    </div>
                @endif
            @endforeach
        </div>
        <form class="send" action="{{ action('MessageController@send') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <input type="file" name="image">
            <input type="hidden" name="order_id" value="{{$order->id}}">
            <input type="text" required="required" class="mess" placeholder="@lang('main.messages.3')" name="body"/>
            <button class="button" type="submit">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <g clip-path="url(#clip0)">
                        <path fill-rule="evenodd" clip-rule="evenodd"
                              d="M6.13527 18.2512L8.75934 13.0023L16.6344 13.0016L6.13527 18.2512ZM16.6343 11.0019L8.75994 11.0019L6.13516 5.7523L16.6343 11.0019ZM22.0162 12.8933C22.0802 12.8217 22.1328 12.7432 22.1726 12.6562C22.1876 12.626 22.2011 12.5958 22.2123 12.5633C22.2537 12.4488 22.2809 12.3289 22.2782 12.2008C22.2754 12.0727 22.2431 11.9514 22.1959 11.8343C22.184 11.8021 22.17 11.772 22.1537 11.7411C22.1086 11.6508 22.0525 11.5685 21.9839 11.4926C21.9679 11.4751 21.9563 11.4563 21.9388 11.4388C21.8613 11.3642 21.7743 11.2976 21.6764 11.2463L3.61363 1.9269C3.20272 1.71562 2.71595 1.78405 2.40191 2.09808C2.08788 2.41212 2.01872 2.89961 2.23073 3.3098L6.64428 11.8648L2.59458 20.2393C2.40076 20.64 2.49018 21.1302 2.81801 21.458C3.14583 21.7859 3.636 21.8753 4.03671 21.6815L21.7154 13.1302C21.8119 13.0824 21.8961 13.0209 21.9698 12.9488C21.988 12.9321 21.9995 12.9115 22.0162 12.8933Z"
                              fill="#999999"/>
                    </g>
                    <defs>
                        <clipPath id="clip0">
                            <rect width="24" height="24" fill="white"/>
                        </clipPath>
                    </defs>
                </svg>
            </button>
        </form>
    </div>
    <br><br>
@endsection

resources/views/frontend/messages.blade.php
@extends('layouts.frontend')

@section('content')
    <br>
    <div class="container">
        <div class="category__all">@lang('main.messages.0')</div>
        <br>
        <div class="messages">
            @foreach($messages as $message)
                <a
                    href="{{action('PageController@message',$message->order_id)}}"
                    class="block">
                    <div class="image">
                        <img src="" alt="">
                    </div>
                    <div class="info">
                        <div class="flex-1">
                            <div class="bold">№ {{$message->order_id}}</div>
                            <div class="bold m-10">{{$message->order->order_item[0]->name}}</div>
                            <div class="light m-10">{{$message->body}}</div>
                        </div>
                        <div class="date">
                            <div class="light">{{\Carbon\Carbon::parse($message->created_at)->format('d-m-yy')}}</div>
                            {{--                            <div class="count m-10">5</div>--}}
                        </div>
                    </div>
                </a>
            @endforeach
        </div>
    </div>
    <br>
@endsection

resources/views/frontend/oldsearch.blade.php
@extends('layouts.frontend')

@section('content')
    <div class="container">
        <div class="main-title">
            {{$category->name ?? $keyword}}
        </div>
        <div class="filter">
            <div class="filter-wrapper">
{{--                <div class="filter-content">--}}
{{--                    <ul class="filter-content__ul">--}}
{{--                        <li><a href="{{action('PageController@category',[$category->alias,'price'])}}" class="active">По цене</a></li>--}}
{{--                        <li><a href="{{action('PageController@category',[$category->alias,'created_at'])}}">По новизне</a></li>--}}
{{--                        <li><a href="{{action('PageController@category',[$category->alias])}}">По дате</a></li>--}}
{{--                        <li><a href="{{action('PageController@category',$category->alias)}}">По продоваемости</a></li>--}}
{{--                        <li><a href="{{action('PageController@category',$category->alias)}}">По скидкам</a></li>--}}
{{--                    </ul>--}}
{{--                </div>--}}
            </div>
        </div>
        <div class="section-product">
            <div class="section-product-wrapper">
                <div class="section-product-card">
                    @foreach($products as $product)
                        @include('partials.product')
                    @endforeach
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/frontend/showCategory.blade.php
@extends('layouts.frontend')

@section('content')
    <br>
    <div class="category">
        <div class="container">
            <div class="category__all">
                {{$category->name}}
            </div>
            <div class="category__choice d-flex align-items-center justify-content-between flex-wrap">
                @foreach($category->sub_category as $item)
                    <a href="{{action('PageController@category',$item->alias)}}"
                       class="category__all btn">{{$item->name}}</a>
                @endforeach
            </div>
            <div class="section-product result d-flex flex-wrap">
                @foreach($products as $product)
                    @include('partials.product')
                @endforeach
            </div>
        </div>
    </div>
@endsection

resources/views/frontend/top.blade.php
@extends('layouts.frontend')

@section('content')
<div class="top-sale">
    <div class="container">
        <div class="category__all">Топ продаж</div>
        <div class="section-product result d-flex flex-wrap">
            @foreach($products as $product)
                @include('partials.product-premium')
            @endforeach
        </div>
    </div>
</div>
@endsection